import { dateFormatter, today } from "@/app/core/helpters";

export const users: User[] = [
	{
		id: "U0",
		username: "Ana Sanchez",
		email: "anasanchez@mail.com",
		userType: "nurse",
		superadmin: true
	},
	{
		id: "U1",
		username: "Doctor1",
		email: "doctor1@mail.com",
		userType: "surgeon",
		superadmin: false
	},
	{
		id: "U2",
		username: "Doctor2",
		email: "doctor2@mail.com",
		superadmin: false,
		userType: "surgeon",
	},
	{
		id: "U3",
		username: "Admin1",
		email: "admin1@mail.com",
		superadmin: false,
		userType: "admin",
		surgeon: "Doctor1",
	},
	{
		id: "U4",
		username: "Admin2",
		email: "admin2@mail.com",
		superadmin: false,
		userType: "admin",
		surgeon: "Doctor2",
	},
	{
		id: "U5",
		username: "Nurse1",
		email: "nurse1@mail.com",
		superadmin: false,
		userType: "nurse",
	},
	{
		id: "U6",
		username: "Nurse2",
		email: "nurse2@mail.com",
		superadmin: false,
		userType: "nurse",
	},
	{
		id: "U7",
		username: "Nurse3",
		email: "nurse3@mail.com",
		superadmin: false,
		userType: "nurse",
	},
];

export const patients: Patient[] = [
	{
		id: "P0",
		patientName: "Patient0",
		surgery: "SurgeryExample",
		surgeryDate: dateFormatter(new Date("September 2, 2023")),
		firstVisit: today,
		phoneNumber: "6123-4567",
		surgeon: "Doctor2",
		address: "Alla",
		notes: "",
		nurse: "Ana Sanchez",
	},
	{
		id: "P1",
		patientName: "Patient1",
		surgery: "SurgeryExample2",
		surgeryDate: dateFormatter(new Date("August 29, 2023")),
		firstVisit: dateFormatter(new Date("August 30, 2023")),
		phoneNumber: "6123-7890",
		surgeon: "Doctor2",
		address: "Ahi",
		notes: "",
		nurse: "Ana Sanchez",
	},
	{
		id: "P2",
		patientName: "Patient2",
		surgery: "SurgeryExample3",
		surgeryDate: dateFormatter(new Date("September 4, 2023")),
		firstVisit: dateFormatter(new Date("September 5, 2023")),
		phoneNumber: "6098-4567",
		surgeon: "Doctor1",
		address: "aqui",
		notes: "tough surgery",
		nurse: "",
	},
	{
		id: "P3",
		patientName: "Patient3",
		surgery: "SurgeryExample",
		surgeryDate: dateFormatter(new Date("September 2, 2023")),
		firstVisit: dateFormatter(new Date("September 3, 2023")),
		phoneNumber: "6123-0987",
		surgeon: "Doctor2",
		address: "Alla",
		notes: "",
		nurse: "",
	},
	{
		id: "P4",
		patientName: "Patient4",
		surgery: "SurgeryExample",
		surgeryDate: dateFormatter(new Date("September 2, 2023")),
		firstVisit: dateFormatter(new Date("September 3, 2023")),
		phoneNumber: "6123-4567",
		surgeon: "Doctor1",
		address: "Alla",
		notes: "papitas",
		nurse: "",
	},
	{
		id: "P5",
		patientName: "Patient5",
		surgery: "SurgeryExample",
		surgeryDate: dateFormatter(new Date("September 2, 2023")),
		firstVisit: dateFormatter(new Date("September 3, 2023")),
		phoneNumber: "6123-4567",
		surgeon: "Doctor1",
		address: "Alla",
		notes: "",
		nurse: "",
	},
	{
		id: "P6",
		patientName: "Patient6",
		surgery: "SurgeryExample",
		surgeryDate: dateFormatter(new Date("September 2, 2023")),
		firstVisit: dateFormatter(new Date("September 3, 2023")),
		phoneNumber: "6123-4567",
		surgeon: "Doctor1",
		address: "Alla",
		notes: "",
		nurse: "",
	},
	{
		id: "P7",
		patientName: "Patient7",
		surgery: "SurgeryExample",
		surgeryDate: dateFormatter(new Date("September 2, 2023")),
		firstVisit: today,
		phoneNumber: "6123-4567",
		surgeon: "Doctor2",
		address: "Alla",
		notes: "big cut",
		nurse: "Nurse3",
	},
	{
		id: "P8",
		patientName: "Patient8",
		surgery: "SurgeryExample",
		surgeryDate: dateFormatter(new Date("September 2, 2023")),
		firstVisit: dateFormatter(new Date("September 3, 2023")),
		phoneNumber: "6123-4567",
		surgeon: "Doctor2",
		address: "Alla",
		notes: "open wound",
		nurse: "Nurse2",
	},
	{
		id: "P9",
		patientName: "Patient9",
		surgery: "SurgeryExample",
		surgeryDate: dateFormatter(new Date("September 2, 2023")),
		firstVisit: dateFormatter(new Date("September 3, 2023")),
		phoneNumber: "6123-4567",
		surgeon: "Doctor1",
		address: "Alla",
		notes: "",
		nurse: "Nurse1",
	},
];
